// packages/typst.angular/projects/demo/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { AppService } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass'],
})
export class AppComponent implements OnInit {
  title = 'Typst.Angular';
  artifact = '';

  constructor(private service: AppService) {}

  ngOnInit() {
    this.service.getArtifact().subscribe(artifact => {
      this.artifact = artifact;
    });
  }
}

<h1 style="color: white; font-size: 20px; font-family: 'Garamond', sans-serif; margin: 20px">
  Demo: Embed Your Typst Document in Angular
</h1>

<typst-document fill="#343541" artifact="{{ artifact }}"></typst-document>

<router-outlet></router-outlet>

// packages/typst.react/src/demo/App.tsx
import { useEffect, useState } from 'react';
import { TypstDocument } from '../lib';

export const App = () => {
  const [artifact, setArtifact] = useState<string>('');

  const getArtifactJson = async () => {
    const response = await fetch('/main.artifact.json').then(response => response.text());

    setArtifact(response);
  };

  useEffect(() => {
    getArtifactJson();
  }, []);

  return (
    <div>
      <h1
        style={{
          color: 'white',
          fontSize: '20px',
          fontFamily: `'Garamond', sans-serif`,
          margin: '20px',
        }}
      >
        Demo: Embed Your Typst Document in React
      </h1>
      <TypstDocument fill="#343541" artifact={artifact} />
    </div>
  );
};
