// packages/typst.angular/projects/typst.angular/src/lib/typst.document.component.ts
import { Component, ElementRef, Input, ViewChild } from '@angular/core';
import { withGlobalRenderer } from '@myriaddreamin/typst.ts/dist/contrib/global-renderer';
import * as typst from '@myriaddreamin/typst.ts';

@Component({
  selector: 'typst-document',
  templateUrl: `./typst.document.component.html`,
  styles: [],
})
export class TypstDocumentComponent {
  _artifact: Uint8Array = new Uint8Array(0);
  @ViewChild('typst_app') typst_app?: ElementRef<HTMLDivElement>;

  @Input() fill: string = '#ffffff';

  @Input()
  set artifact(artifact: Uint8Array) {
    this._artifact = artifact;
    this.applyArtifact();
  }

  get artifact(): Uint8Array {
    return this._artifact;
  }

  constructor() {}

  applyArtifact() {
    if (this.typst_app?.nativeElement) {
      const displayDiv = this.typst_app?.nativeElement;
      if (this.artifact?.length) {
        const doRender = (renderer: typst.TypstRenderer) => {
          console.log(renderer);
          renderer.render({
            artifactContent: this.artifact,
            backgroundColor: this.fill,
            container: displayDiv,
            pixelPerPt: 8,
          });
          return;
        };

        /// render after init
        withGlobalRenderer(
          typst.createTypstRenderer,
          (window as unknown as any).pdfjsLib,
          {
            beforeBuild: [
              typst.preloadRemoteFonts([
                'http://localhost:20810/assets/fonts/LinLibertine_R.ttf',
                'http://localhost:20810/assets/fonts/LinLibertine_RB.ttf',
                'http://localhost:20810/assets/fonts/LinLibertine_RBI.ttf',
                'http://localhost:20810/assets/fonts/LinLibertine_RI.ttf',
                'http://localhost:20810/assets/fonts/NewCMMath-Book.otf',
                'http://localhost:20810/assets/fonts/NewCMMath-Regular.otf',
              ]),
            ],
            getModule: () => '/assets/typst-ts-renderer/pkg/typst_ts_renderer_bg.wasm',
          },
          doRender,
        );
      } else {
        displayDiv.innerHTML = '';
      }
    }
  }
}

<div #typst_app></div>

// packages/typst.react/src/lib/TypstDocument.tsx
import React, { useState, useRef, useEffect } from 'react';
import { withGlobalRenderer } from '@myriaddreamin/typst.ts/dist/esm/contrib/global-renderer';
import * as typst from '@myriaddreamin/typst.ts';

export interface TypstDocumentProps {
  fill?: string;
  artifact: Uint8Array;
  // todo: add vector format
  format?: 'json';
}

let moduleInitOptions: typst.InitOptions = {
  beforeBuild: [
    typst.preloadRemoteFonts([
      '/fonts/LinLibertine_R.ttf',
      '/fonts/LinLibertine_RB.ttf',
      '/fonts/LinLibertine_RBI.ttf',
      '/fonts/LinLibertine_RI.ttf',
      '/fonts/NewCMMath-Book.otf',
      '/fonts/NewCMMath-Regular.otf',
    ]),
  ],
  getModule: () => '/node_modules/@myriaddreamin/typst-ts-renderer/pkg/typst_ts_renderer_bg.wasm',
};

export const TypstDocument = ({ fill, artifact, format }: TypstDocumentProps) => {
  /// --- beg: manipulate permission --- ///

  // todo: acquire permission
  const [permission, setPermissionInternal] = useState(false);
  const setPermissionAndOk = (status: PermissionStatus) => {
    if (status.state === 'granted') {
      setPermissionInternal(true);
      return true;
    }
    setPermissionInternal(false);
    return false;
  };
  useEffect(() => {
    navigator.permissions.query({ name: 'local-fonts' as PermissionName }).then(status => {
      if (setPermissionAndOk(status)) {
        return false;
      }
      status.addEventListener('change', event => {
        console.log(event, status);
        setPermissionAndOk(status);
      });
    });
  });

  /// --- end: manipulate permission --- ///

  /// --- beg: update document --- ///
  const displayDivRef = useRef<HTMLDivElement>(null);
  const getDisplayLayerDiv = () => {
    return displayDivRef?.current;
  };

  useEffect(() => {
    const doRender = (renderer: typst.TypstRenderer) => {
      const divElem = getDisplayLayerDiv();
      if (!divElem) {
        return;
      }

      return renderer.render({
        artifactContent: artifact,
        format: (format == 'json' ? 'js' : undefined) /* never */ || 'js',
        backgroundColor: fill,
        container: divElem,
        pixelPerPt: 8,
      });
    };

    /// get display layer div
    const divElem = getDisplayLayerDiv();
    if (!divElem) {
      return;
    }

    /// we allow empty artifact
    if (!artifact?.length) {
      divElem.innerHTML = '';
      return;
    }

    /// render after init
    withGlobalRenderer(
      typst.createTypstRenderer,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (window as unknown as any).pdfjsLib,
      moduleInitOptions,
      doRender,
    );
  }, [permission, displayDivRef, fill, artifact, format]);

  /// --- end: update document --- ///

  return (
    <div>
      <div className="typst-app" style={{ height: '0' }} ref={displayDivRef}></div>
    </div>
  );
};

TypstDocument.setWasmModuleInitOptions = (opts: typst.InitOptions) => {
  moduleInitOptions = opts;
};
